// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://bkkbn.go.id",
        "contact": {
            "name": "Direktorat Teknologi Informasi dan Data",
            "url": "https://bkkbn.go.id",
            "email": "dittifdok@bkkbn.go.id"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/keluarga": {
            "get": {
                "description": "Get Keluarga Sasaran By Kelurahan",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get Keluarga Sasaran By Kelurahan"
                ],
                "summary": "Get Keluarga Sasaran By Kelurahan",
                "operationId": "get-list-keluarga-sasaran-by-kelurahan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Province Code",
                        "name": "kdprov",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kabupaten Code",
                        "name": "kdkab",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kecamatan Code",
                        "name": "kdkec",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kelurahan Code",
                        "name": "kdkel",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of Keluarga Sasaran per page",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/keluarga.Keluarga"
                        }
                    }
                }
            }
        },
        "/keluargaberesiko": {
            "get": {
                "description": "Get Keluarga Beresiko Stunting By Kelurahan",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get Keluarga Beresiko Stunting By Kelurahan"
                ],
                "summary": "Get Keluarga Beresiko Stunting By Kelurahan",
                "operationId": "get-list-keluarga-beresiko-stunting-by-kelurahan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Province Code",
                        "name": "kdprov",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kabupaten Code",
                        "name": "kdkab",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kecamatan Code",
                        "name": "kdkec",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kelurahan Code",
                        "name": "kdkel",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Peringkat Kesejateraan (0-4)",
                        "name": "filter2",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of Keluarga Beresiko Stunting per page",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/keluarga.Keluarga"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "keluarga.Keluarga": {
            "type": "object",
            "properties": {
                "baduta": {
                    "type": "string"
                },
                "balita": {
                    "type": "string"
                },
                "bukanPesertaKbModern": {
                    "type": "string"
                },
                "idFrm": {
                    "description": "IdFrm                  string ` + "`" + `gorm:\"column:id_frm\"` + "`" + `",
                    "type": "string"
                },
                "idKabupaten": {
                    "type": "integer"
                },
                "idKecamatan": {
                    "type": "integer"
                },
                "idKelurahan": {
                    "type": "integer"
                },
                "idProvinsi": {
                    "type": "integer"
                },
                "jambanLayakTidak": {
                    "type": "string"
                },
                "kesejahteraanPrioritas": {
                    "type": "integer"
                },
                "kodeKabupaten": {
                    "type": "integer"
                },
                "kodeKecamatan": {
                    "type": "integer"
                },
                "kodeKeluarga": {
                    "type": "string"
                },
                "kodeKelurahan": {
                    "type": "integer"
                },
                "kodeProvinsi": {
                    "type": "integer"
                },
                "kodeRt": {
                    "type": "string"
                },
                "kodeRw": {
                    "type": "string"
                },
                "latitude": {
                    "type": "string"
                },
                "longitude": {
                    "type": "string"
                },
                "namaIstri": {
                    "type": "string"
                },
                "namaKabupaten": {
                    "type": "string"
                },
                "namaKecamatan": {
                    "type": "string"
                },
                "namaKelurahan": {
                    "type": "string"
                },
                "namaKepalaKeluarga": {
                    "type": "string"
                },
                "namaProvinsi": {
                    "type": "string"
                },
                "namaRt": {
                    "type": "string"
                },
                "namaRw": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "periode": {
                    "type": "integer"
                },
                "pus": {
                    "type": "string"
                },
                "pusHamil": {
                    "type": "string"
                },
                "risikoStunting": {
                    "type": "string"
                },
                "sumberAirLayakTidak": {
                    "type": "string"
                },
                "terlaluBanyak": {
                    "type": "string"
                },
                "terlaluDekat": {
                    "type": "string"
                },
                "terlaluMuda": {
                    "type": "string"
                },
                "terlaluTua": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.1.1",
	Host:             "gorest-2022-krs-prelist-ds-bkkbn-2022-gorest-krs.apps.ocp-dev.bkkbn.go.id",
	BasePath:         "/v1/api/2022",
	Schemes:          []string{},
	Title:            "BKKBN Digital Service - Keluarga Beresiko Stunting",
	Description:      "Digital Service BKKBN for Integration",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
