basePath: /v1/api/2022/wilayah
definitions:
  kabupaten.Kabupaten:
    properties:
      idKabupaten:
        type: integer
      idProvinsi:
        type: integer
      kodeKabupaten:
        type: integer
      kodeProvinsi:
        type: integer
      namaKabupaten:
        type: string
      namaProvinsi:
        type: string
    type: object
  kecamatan.Kecamatan:
    properties:
      idKabupaten:
        type: integer
      idKecamatan:
        type: integer
      idProvinsi:
        type: integer
      kodeKabupaten:
        type: integer
      kodeKecamatan:
        type: integer
      kodeProvinsi:
        type: integer
      namaKabupaten:
        type: string
      namaKecamatan:
        type: string
      namaProvinsi:
        type: string
    type: object
  kelurahan.Kelurahan:
    properties:
      idKabupaten:
        type: integer
      idKecamatan:
        type: integer
      idKelurahan:
        type: integer
      idProvinsi:
        type: integer
      kodeKabupaten:
        type: integer
      kodeKecamatan:
        type: integer
      kodeKelurahan:
        type: integer
      kodeProvinsi:
        type: integer
      namaKabupaten:
        type: string
      namaKecamatan:
        type: string
      namaKelurahan:
        type: string
      namaProvinsi:
        type: string
    type: object
  provinsi.Provinsi:
    properties:
      idProvinsi:
        type: integer
      kodeProvinsi:
        type: integer
      namaProvinsi:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: dittifdok@bkkbn.go.id
    name: Direktorat Teknologi Informasi dan Data
    url: https://bkkbn.go.id
  description: Digital Service BKKBN for Integration - Wilayah Service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://bkkbn.go.id
  title: BKKBN Digital Service - Wilayah
  version: 2.2.0
paths:
  /showkabupaten:
    get:
      consumes:
      - '*/*'
      description: Get Wilayah By Kabupaten
      operationId: get-list-wilayah-by-kabupaten
      parameters:
      - description: Province Code
        in: query
        name: kdprov
        required: true
        type: string
      - description: Page Number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of Kabupaten per page
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kabupaten.Kabupaten'
      summary: Get Wilayah By Kabupaten
      tags:
      - Get Wilayah By Kabupaten
  /showkecamatan:
    get:
      consumes:
      - '*/*'
      description: Get Wilayah By Kecamatan
      operationId: get-list-wilayah-by-kecamatan
      parameters:
      - description: Province Code
        in: query
        name: kdprov
        required: true
        type: string
      - description: Kabupaten Code
        in: query
        name: kdkab
        required: true
        type: string
      - description: Page Number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of Kecamatan per page
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kecamatan.Kecamatan'
      summary: Get Wilayah By Kecamatan
      tags:
      - Get Wilayah By Kecamatan
  /showkelurahan:
    get:
      consumes:
      - '*/*'
      description: Get Wilayah Sasaran By Kelurahan
      operationId: get-list-wilayah-by-kelurahan
      parameters:
      - description: Province Code
        in: query
        name: kdprov
        required: true
        type: string
      - description: Kabupaten Code
        in: query
        name: kdkab
        required: true
        type: string
      - description: Kecamatan Code
        in: query
        name: kdkec
        required: true
        type: string
      - description: Page Number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of Kelurahan per page
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kelurahan.Kelurahan'
      summary: Get Wilayah By Kelurahan
      tags:
      - Get Wilayah By Kelurahan
  /showprovinsi:
    get:
      consumes:
      - '*/*'
      description: Get Wilayah by Province
      operationId: get-wilayah-by-province
      parameters:
      - default: 34
        description: Number of Province per page
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/provinsi.Provinsi'
      summary: Get Wilayah by Province
      tags:
      - Get Wilayah by Province
swagger: "2.0"
